# Configuration for promtail chart, see https://github.com/grafana/helm-charts/tree/main/charts/promtail

config:
  # publish data to loki
  clients:
    - url: http://loki:3100/loki/api/v1/push
      # We have to set the tenant_id/OrgID to push logs to Loki
      # otherwise we get an auth error.
      tenant_id: 1

  snippets:
    pipelineStages:
      # Parse cluster and machine to make them available as labels.
      - cri: {}
      - json:
          expressions:
            controller:
            cluster: join('/',[Cluster.namespace,Cluster.name])
            machine: join('/',[Machine.namespace,Machine.name])
      - labels:
          controller:
          cluster:
          machine:
