name: PR verify

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  checks: write # Allow access to checks to write check runs.

jobs:
  verify:
    runs-on: ubuntu-latest
    name: verify PR contents
    steps:
    - name: Verifier action
      id: verifier
      uses: kubernetes-sigs/kubebuilder-release-tools@e389278c2051863fb39b8de00159c8d7fac760ea # tag=v0.4.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
